
{
    'name': "CRM Dashboard",
    'version': '17.0.1.0.0',
    'category': 'Extra Tools',
    'author': 'Abdalrahman Shahrour',
    'company': 'PyShbak',
    'website': "https://www.linkedin.com/in/shahrour/",
    'depends': ['crm', 'sale_management'],
    'data': ['views/crm_team_views.xml',
             'views/res_users_views.xml',
             'views/utm_campaign_views.xml',
             ],
    'assets': {
        'web.assets_backend': [
            'crm_dashboard/static/src/css/dashboard.css',
            'crm_dashboard/static/src/css/style.scss',
            'crm_dashboard/static/src/css/material-gauge.css',
            'crm_dashboard/static/src/js/crm_dashboard.js',
            'crm_dashboard/static/src/js/lib/highcharts.js',
            'crm_dashboard/static/src/js/lib/Chart.bundle.js',
            'crm_dashboard/static/src/js/lib/funnel.js',
            'crm_dashboard/static/src/js/lib/d3.min.js',
            'crm_dashboard/static/src/js/lib/material-gauge.js',
            'crm_dashboard/static/src/js/lib/columnHeatmap.min.js',
            'crm_dashboard/static/src/js/lib/columnHeatmap.js',
            'crm_dashboard/static/src/xml/dashboard_templates.xml',
        ],
    },
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
